sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fn5QIrltoAkhzoZUA37LeAYhSAiCk46Fp8VA8j7crNtaGjyWvppS5QaYbGZTYDpy+zmLqgFWeENmtNrZawAN8uDjcaMPW7Imjh6i16+zITEhzDeGCsFWUP4PfAnFhsWI3zo5qjeAmWqFX7+etX56+MfIRjjKE8vsKWVKoCA4bgo+IX859LI7xzLhKBTkAifNuTCK5X32D/pfMmqqf/dQJlMr0a/pjsNym5MHoFAhRBiNQpl80PhXjw9WkwJF78MziRdFAzhzxR4dyN9mIjw0GOTN5CyNdA8RvdAMiFO84carfmdmIjaLEWgqlxrV4Rs9a1yJSz6IJaiarFS/rJRr4Lboszimd0YwYT0u9HCg60STUq6t4w+wNAPKeyCd+hItIwD1x5pXMEjwBGULhYWE9QL2CeuMrps63sQHBWFJvrxinPWIhznHYwmeRle1ZQ5LG9d8VHy5NbyVAwYU+19mEi5+vpPD1BVtCozb9aPIqAfwdNB1Y7XmBV5lqWmFjEu3BNVVJWCn8GF/xweMZZxPPokzyGR8NkcPQBbIzpXdDu+wkFtlfUQhDCZDArgpx5H+TNACcJTfm4Jza802EitioTy+GgBqHKU13vrSWkTYJOTcyVSQlSfqb0V+jmNUvfqxD3NrAWTyXDRifHw3ULrCbdwtLJkBWiJpG8Mvm4teGEg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Puzzle-of-Dickens-s-Last-Plot_738
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy